name: Go Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Docker
        run:
          sudo apt-get update
          sudo apt-get install docker.io=1.43
          sudo systemctl start docker
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.6'

    - name: Start PostgreSQL
      run: docker run --name postgres -e POSTGRES_PASSWORD=12345 -d -p 5432:5432 postgres:latest

    - name: Test handlers
      run: cd app/handlers && go test -v

    - name: Test database connection
      run: cd db && go test -v

    - name: Test container
      run: cd app/services && go test -v